---
- name: Setup redhat
  block:
    - name: update all packages
      yum:
        name: "*"
        state: latest

    - name: add epel repo
      yum:
        name: epel-release
        state: latest

    - name: install dependencies
      yum:
        name: ['jq', 'git', 'unzip', 'p7zip', 'bsdtar']
        state: latest
  when: ansible_os_family == "RedHat"
